import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/SideNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen w-full bg-white text-black flex", inter.className, { "debug-screens": process.env.NODE_ENV === "development" })}>

        {/* sidebar */}
        <SideNavbar />
        {/* maindiv */}
        <div className="px-8 py-5 w-full min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
